spring:
  profiles:
    include:
      - graphql.playground
      - graphql.voyager
  zipkin:
    enabled: false
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    exampler:
#      probability: 1
server:
  port: 8401
arc:
  graphql:
    define: graphql/*.graphqls