graphql.playground:
  mapping: /playground
  endpoint: /schema
  enabled: true
  pageTitle: GraphqlExample
  cdn:
    enabled: false
  settings:
    editor.cursorShape: line
    editor.fontFamily: "'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace"
    editor.fontSize: 14
    editor.reuseHeaders: true
    editor.theme: dark
    prettier.printWidth: 80
    prettier.tabWidth: 2
    prettier.useTabs: false
    request.credentials: omit
    schema.polling.enable: false
    schema.polling.interval: 20000
    schema.disableComments: false
    tracing.hideTracingResponse: true
  headers:
    Authorization: admin
    Namespace: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lc3BhY2UiOiIweDIifQ.uM_gyrCmoqyS81rJtgzxrl_gqZumgXK4lvmwmJSH3mk
  tabs:
    - name: projectQuery
      query: classpath:graphql/embed/projectQuery.graphql
      variables: classpath:graphql/embed/variables.json
      responses:
        - classpath:graphql/embed/projectResponse.json
    - name: Create Project
      query: classpath:graphql/embed/projectCreate.graphql
